#!/usr/bin/ruby
require 'rubygems'
require 'cli'
require 'httpclient'

settings = CLI.new do
    option :server, :description => 'server address', :default => 'www.google.com'
    option :port, :description => 'server port', :cast => Integer, :default => 80
    argument :url, :description => 'URL to GET or POST to if arguments are given'
    arguments :post_arguments, :required => false
end.parse! do |settings|
    fail "invalid URL '#{settings.url}', URL has to start with '/'" unless settings.url =~ /^\//
end

c = HTTPClient.new

begin
    if settings.post_arguments.empty?
        puts c.get_async("http://#{settings.server}:#{settings.port}#{settings.url}").pop.content.read
    else
        puts c.post_async("http://#{settings.server}:#{settings.port}#{settings.url}", settings.post_arguments.join("\n")).pop.content.read
    end 
rescue SocketError, Errno::ECONNREFUSED => e
    puts "Falied to connect: #{e}"
end

