#!/usr/bin/ruby -rrubygems
require 'cli'
require 'pathname'

values = CLI.new do
	description 'Lists content of directories'
	switch :long, :short => :l, :description => 'use long listing'
	options :exclude, :short => :e, :description => 'exclude files from listing'
	arguments :directories,	:cast => Pathname, :default => '.', :description => 'directories to list content of'
end.parse!

values.directories.each do |dir|
	next unless dir.directory?
	dir.each_entry do |e|
		next if e.to_s == '.' or e.to_s == '..'
		e = dir + e
		next if values.exclude.include? e.to_s
		if values.long
			puts "#{e.stat.uid}:#{e.stat.gid} #{e}"
		else
			puts e
		end
	end
end

