#!/usr/bin/ruby
require 'pathname'
cli_root = Pathname.new(__FILE__).dirname + '..'
$LOAD_PATH.unshift(cli_root + 'lib')

require 'cli'

options = CLI.new do
	description 'Lists content of directories'
	switch :long, :short => :l, :description => 'use long listing'
	arguments :directories,	:cast => Pathname, :default => '.', :description => 'directories to list content of'
end.parse!

options.directories.each do |dir|
	next unless dir.directory?
	dir.each_entry do |e|
		next if e.to_s == '.' or e.to_s == '..'
		e = dir + e
		if options.long
			puts "#{e.stat.uid}:#{e.stat.gid} #{e}"
		else
			puts e
		end
	end
end

