#!/usr/bin/ruby
require 'rubygems'
require 'cli'
require 'pathname'

settings = CLI.new do
	description 'Lists content of directories'
	switch :long, :short => :l, :description => 'use long listing'
	options :exclude, :short => :e, :description => 'exclude files from listing'
	arguments :directories,	:cast => Pathname, :default => '.', :description => 'directories to list content of'
end.parse!

settings.directories.each do |dir|
	next unless dir.directory?
	dir.each_entry do |e|
		next if e.to_s == '.' or e.to_s == '..'
		e = dir + e
		next if settings.exclude.include? e.to_s
		if settings.long
			puts "#{e.stat.uid}:#{e.stat.gid} #{e}"
		else
			puts e
		end
	end
end

